// https://app.quicktype.io/

// To parse this JSON data, do
//
//     final character = characterFromJson(jsonString);

import 'package:initiative_tracker/models/campaign.dart';
import 'package:initiative_tracker/models/user.dart';

// Generated by https://javiercbk.github.io/json_to_dart/

class Character {
  int? id;
  String? name;
  String? rolClass;
  String? race;
  int? level;
  String? picture;
  String? description;
  String? notes;
  bool? isActive;
  String? createdAt;
  String? updatedAt;
  String? deletedAt;
  Campaign? campaign;
  User? user;

  Character(
      {this.id,
      this.name,
      this.rolClass,
      this.race,
      this.level,
      this.picture,
      this.description,
      this.notes,
      this.isActive,
      this.createdAt,
      this.updatedAt,
      this.deletedAt,
      this.campaign,
      this.user});

  Character.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    name = json['name'];
    rolClass = json['rolClass'];
    race = json['race'];
    level = json['level'];
    picture = json['picture'];
    description = json['description'];
    notes = json['notes'];
    isActive = json['isActive'];
    createdAt = json['createdAt'];
    updatedAt = json['updatedAt'];
    deletedAt = json['deletedAt'];
    campaign =
        json['campaign'] != null ? Campaign.fromJson(json['campaign']) : null;
    user = json['user'] != null ? User.fromJson(json['user']) : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    data['rolClass'] = rolClass;
    data['race'] = race;
    data['level'] = level;
    data['picture'] = picture;
    data['description'] = description;
    data['notes'] = notes;
    data['isActive'] = isActive;
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    data['deletedAt'] = deletedAt;
    if (campaign != null) {
      data['campaign'] = campaign!.toJson();
    }
    if (user != null) {
      data['user'] = user!.toJson();
    }
    return data;
  }

  Character copy() => Character(
        id: id,
        name: name,
        rolClass: rolClass,
        race: race,
        level: level,
        picture: picture,
        description: description,
        notes: notes,
        isActive: isActive,
        createdAt: createdAt,
        updatedAt: updatedAt,
      );
}

// ////////////////////////////////////////////////////////// OLD ///////////////////////////////////
// class CharacterOld {
//   CharacterOld({
//     this.id,
//     required this.name,
//     required this.rolClass,
//     required this.race,
//     required this.level,
//     this.picture,
//     required this.description,
//     required this.notes,
//     required this.isActive,
//     this.createdAt,
//     this.updatedAt,
//   });

//   int? id;
//   String name;
//   String rolClass;
//   String race;
//   int level;
//   String? picture;
//   String description;
//   String notes;
//   bool isActive;
//   DateTime? createdAt;
//   DateTime? updatedAt;

//   factory CharacterOld.fromRawJson(String str) =>
//       CharacterOld.fromJson(json.decode(str));

//   String toRawJson() => json.encode(toJson());

//   factory CharacterOld.fromJson(Map<String, dynamic> json) => CharacterOld(
//         id: json["id"],
//         name: json["name"],
//         rolClass: json["rolClass"],
//         race: json["race"],
//         level: json["level"],
//         picture: json["picture"],
//         description: json["description"],
//         notes: json["notes"],
//         isActive: json["isActive"],
//         createdAt: DateTime.parse(json["createdAt"]),
//         updatedAt: DateTime.parse(json["updatedAt"]),
//       );

//   Map<String, dynamic> toJson() => {
//         "id": id,
//         "name": name,
//         "rolClass": rolClass,
//         "race": race,
//         "level": level,
//         "picture": picture,
//         "description": description,
//         "notes": notes,
//         "isActive": isActive,
//         "createdAt": createdAt?.toIso8601String(),
//         "updatedAt": updatedAt?.toIso8601String(),
//       };

//   CharacterOld copy() => CharacterOld(
//         id: id,
//         name: name,
//         rolClass: rolClass,
//         race: race,
//         level: level,
//         picture: picture,
//         description: description,
//         notes: notes,
//         isActive: isActive,
//         createdAt: createdAt,
//         updatedAt: updatedAt,
//       );
// }
